development: &default
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://qa-alumni.k2practice.com/login
  system_url: https://qa-alumni.k2practice.com
  portal_url: https://qa-hub.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>


int:
  <<: *default
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://stage-alumni.k2practice.com/login
  system_url: https://int-alumni.k2practice.com
  portal_url: https://int-hub.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>

qa:
  <<: *default
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://qa-alumni.k2practice.com/login
  system_url: https://qa-alumni.k2practice.com
  portal_url: https://qa-hub.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>

demo:
  <<: *default
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://demo-alumni.k2practice.com/login
  system_url: https://demo-alumni.k2practice.com
  portal_url: https://demo-hub.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>

stage:
  <<: *default
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://stage-alumni.k2practice.com/login
  system_url: https://stage-alumni.k2practice.com
  portal_url: https://stage-hub.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>

production:
  token: 46f17cdb2b97ac3398efdd9d55bdcababcef8a603d70abd93b647c6922796b77c188ddcc32df930ebd0024ae8da61be14d7b22de5d664069ca69b76a2b9a5024
  login: https://alumni.k2practice.com/login
  redir_url: https://quest.k2practice.com
  system_url: https://alumni.k2practice.com
  access_token: <%= ENV["STAGE_SYSTEM_ACCESS_TOKEN"] %>
  prod_access_token: <%= ENV["PROD_SYSTEM_ACCESS_TOKEN"] %>


