development: &default
  key: "BwIAAACkAABSU0EyAAQAAAEAAQBR9jjzTHl64QYvol%2FnHssnkOG%2BgI5QeglRJsANAjZ7UQ411cspTzPc8m54ORrHksmPDHL1rjsiwJsliJJbLvkZWXY0wJrTW6NlEaEwA%2BgSm9blUv0ss5QpvbS%2F9CA1%2Fsl9CCo3ZXv1c%2Fn6C4nOrLmXQ%2F9iIn46X9dxlG23KA9sviFPKbOAe5QfFaZDQgaCGkVixWyz%2B%2BJ4YeA7%2Be8yr7JLV2ndN6Lf20SRo35OQYM%2FEkLSDuJrkyue%2FkD%2B6IR79c4xsTtcFqrGrudGQ%2FHeBRGTSPiihiF%2B7jj7sVmHF5ws8oOsJnklRfhM7ObK%2BVfoqFYMTGbUJZt%2FySPIMoY2bIvrQT6BIGVwnUQdFWs2NbXKqfYUagp8HEQfk8YGHw6cqc71of7NWGOx7WRYPJKe5NhtTsMyJVGZVO%2BEX9wx2vrqHYHgPmlXRpy%2BPOQUM%2Bl%2Bf7niVI%2BKxyRvwfpgF4bRXApSLkXMQMRhQIC6L0Yp6JBs36ljPp9VlItuObcv6d3RnQKZB1y6lfIW8vwmfdHdQqntx%2FEC585kQJ1cnClB%2Bi3BOZzr0e%2F5MxKViNBv%2BF6vfWyvZ%2FSstmFwEJNlAZsDi3F6gcOMAZq9eNd3xsXa5C%2BF7cmWui2LecdMEbnou51My9sRXgAsswP%2Fy3XwgfRuxI7DAShipoXRumDF7DxUawfrvo2SVWzmqPOEHx2RFR9VH4ii9mX%2F4gJefdeGSxS3H%2BdHs1iIJuQuduV0amxZGpBbbn1QpNdmOLefWO%2Fbp8mhBgI%3D"


staging:
  <<: *default

production:
  <<: *default
