development: &default
  host: "localhost"
  port: 6379
  url: "redis://localhost:6379"
  namespace: "quest-development"

test:
  <<: *default
  namespace: "quest-test"

staging:
  <<: *default
  namespace: "quest-staging"

production:
  <<: *default
  namespace: "quest-production"
